spring.application.name=dungeons-dragons-api
spring.profiles.active=dev

# Mova estas 3 linhas para cá, no arquivo principal:
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Garanta a porta aqui
server.port=8081

# Configurações de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true